// Adapted from EnergyAI/PFE2-main-release: energy-scene.tsx and projected-site.tsx.
// Both renderers retain the original 360 × 360 site coordinates.
const project=([x,y,z])=>{const turn=-34*Math.PI/180,tilt=58*Math.PI/180;const rx=(x-180)*Math.cos(turn)-(y-180)*Math.sin(turn),ry=(x-180)*Math.sin(turn)+(y-180)*Math.cos(turn);return `${(260+rx).toFixed(2)},${(250+ry*Math.cos(tilt)-z*Math.sin(tilt)).toFixed(2)}`};
const polygon=points=>points.map(project).join(' ');
const line=points=>`M${points.map(project).join('L')}`;
function solar(x,y,w,d,z){let out=`<g stroke="#8abed8" stroke-width=".7"><polygon fill="#173e69" points="${polygon([[x,y,z],[x+w,y,z],[x+w,y+d,z],[x,y+d,z]])}"/>`;for(let i=0;i<4;i++)out+=`<path fill="none" d="${line([[x,y+d*(i+1)/5,z],[x+w,y+d*(i+1)/5,z]])}"/>`;return out+`<path fill="none" d="${line([[x+w/2,y,z],[x+w/2,y+d,z]])}"/></g>`}
function building(x,y,w,d,h,windows=false){let out=`<g stroke="#4f83ad" stroke-width=".8"><polygon fill="#1c4068" points="${polygon([[x,y,0],[x,y+d,0],[x,y+d,h],[x,y,h]])}"/><polygon fill="#32618f" points="${polygon([[x,y+d,0],[x+w,y+d,0],[x+w,y+d,h],[x,y+d,h]])}"/>`;if(windows)for(let row=0;row<5;row++)for(let col=0;col<5;col++){const z=6+row*22,dx=x+5+col*20,dy=y+4+col*18;out+=`<g stroke="#163252" stroke-width="2"><polygon fill="#8abedf" points="${polygon([[dx,y+d,z],[dx+15,y+d,z],[dx+15,y+d,z+16],[dx,y+d,z+16]])}"/><polygon fill="#4d83ae" points="${polygon([[x,dy,z],[x,dy+13,z],[x,dy+13,z+16],[x,dy,z+16]])}"/></g>`}return out+`<polygon fill="#52799f" points="${polygon([[x,y,h],[x+w,y,h],[x+w,y+d,h],[x,y+d,h]])}"/><polygon fill="none" stroke="#a9c5df" points="${polygon([[x+4,y+4,h],[x+w-4,y+4,h],[x+w-4,y+d-4,h],[x+4,y+d-4,h]])}"/></g>`}
function projectedSite(){const routes=[[[0,265,1],[100,265,1],[100,230,1],[180,230,1],[180,160,1],[300,160,1],[300,0,1]],[[0,120,1],[65,120,1],[65,160,1],[180,160,1]],[[180,360,1],[180,270,1],[290,270,1],[290,160,1],[360,160,1]]];let out=`<svg class="projectedSite" viewBox="0 0 520 440" aria-hidden="true"><defs><radialGradient id="site-tree" cx="30%" cy="30%"><stop stop-color="#8fd0ee"/><stop offset="1" stop-color="#2f6794"/></radialGradient></defs><polygon fill="#091629" stroke="#35689a" stroke-width="2" points="${polygon([[0,0,-10],[360,0,-10],[360,360,-10],[0,360,-10]])}"/><polygon fill="#0e1d35" stroke="#6c99c0" points="${polygon([[0,0,0],[360,0,0],[360,360,0],[0,360,0]])}"/><g stroke="#60a5fa17" fill="none">`;for(let i=1;i<12;i++)out+=`<path d="${line([[i*30,0,0],[i*30,360,0]])}${line([[0,i*30,0],[360,i*30,0]])}"/>`;out+='</g><g fill="none" stroke="#3ea4df55" stroke-width="2">';for(const route of routes)out+=`<path d="${line(route)}"/><path class="energyPulse" d="${line(route)}"/>`;out+='</g>';for(let i=0;i<3;i++)out+=solar(28+i*27,54,22,52,7);for(let i=0;i<3;i++){const [cx,cy]=project([320,50+i*39,12]).split(',');out+=`<ellipse cx="${cx}" cy="${cy}" rx="12" ry="7" fill="url(#site-tree)"/>`}out+=building(115,86,105,94,116,true)+solar(132,100,65,36,117)+building(112,180,103,76,55)+solar(121,189,85,58,56)+building(264,215,37,43,42);out+=`<path fill="none" stroke="#7dd3fc" stroke-width="2" d="${line([[283,226,43],[275,237,43],[287,237,43],[280,247,43]])}"/>`;for(const point of [[65,120,1],[290,270,1],[100,265,1]]){const [cx,cy]=project(point).split(',');out+=`<ellipse cx="${cx}" cy="${cy}" rx="4" ry="2.5" fill="#7dd3fc" stroke="#7dd3fc33" stroke-width="5"/>`}return out+'</svg>'}
export function mountEnergyScene(scene,isPaused){
 scene.innerHTML=`<div class="sceneHalo"></div><div class="orbitOne"></div><div class="orbitTwo"></div><div class="sceneModel"><div class="platform"><div class="platformEdge"></div><svg class="energyPaths" viewBox="0 0 360 360" aria-hidden="true"><path d="M0 265H100V230H180V160H300V0M0 120H65V160H180M180 360V270H290V160H360"/><path class="energyPulse" d="M0 265H100V230H180V160H300V0M0 120H65V160H180M180 360V270H290V160H360"/><circle cx="180" cy="230" r="5"/><circle cx="290" cy="270" r="5"/><circle cx="65" cy="120" r="5"/></svg><div class="building mainBuilding" style="--height:116px"><div class="buildingFront"></div><div class="buildingSide"></div><div class="buildingRoof" data-depth-probe><span class="roofMark">E / 01</span><div class="roofEquipment"></div></div></div><div class="building annex" style="--height:55px"><div class="buildingFront"></div><div class="buildingSide"></div><div class="buildingRoof"><div class="solarPanels"></div></div></div><div class="building battery" style="--height:42px"><div class="buildingFront"></div><div class="buildingSide"></div><div class="buildingRoof">ϟ</div></div><div class="groundPanels"><div></div><div></div><div></div></div><div class="siteLabel">ENERGYAI / CONNECTED SITE</div><div class="siteTrees"><i></i><i></i><i></i></div></div></div>${projectedSite()}<div class="sceneTag sourceTag"><span class="tagIcon">ϟ</span><div><small>01 / CONNECT</small><strong>Meter readings</strong></div></div><div class="sceneTag forecastTag"><span class="tagIcon">⌘</span><div><small>02 / UNDERSTAND</small><strong>Forecast intelligence</strong></div></div><div class="sceneTag actionTag"><span>↗</span><span>Measure. Understand. Act.</span></div><div class="sceneCoordinates">SINGLE SITE<br><span>ISOMETRIC VIEW / 01</span></div>`;
 const roof=scene.querySelector('[data-depth-probe]');const elevated=roof.getBoundingClientRect().top;roof.style.transform='translateZ(0)';const flat=roof.getBoundingClientRect().top;roof.style.removeProperty('transform');scene.dataset.flat=String(Math.abs(elevated-flat)<1);
 let pointerX=0,pointerY=0,visible=true,step=0;const story=scene.closest('.energy-story');
 function update(){if(!visible||document.hidden)return;const still=isPaused();const rect=story.getBoundingClientRect();const progress=still?0:Math.max(0,Math.min(1,(-rect.top+innerHeight*.2)/Math.max(story.offsetHeight-innerHeight*.5,1)));scene.style.setProperty('--scene-turn',`${-34+progress*24+(still?0:pointerX*8)}deg`);scene.style.setProperty('--scene-tilt',`${58-progress*7+(still?0:pointerY*4)}deg`);scene.style.setProperty('--scene-rise',`${progress*-14}px`);scene.style.setProperty('--scene-sway',`${still?0:progress*3+pointerX*2}deg`);}
 scene.addEventListener('pointermove',event=>{if(!matchMedia('(pointer:fine)').matches||isPaused())return;const r=scene.getBoundingClientRect();pointerX=(event.clientX-r.left)/r.width-.5;pointerY=(event.clientY-r.top)/r.height-.5;update()});scene.addEventListener('pointerleave',()=>{pointerX=pointerY=0;update()});new IntersectionObserver(([entry])=>{visible=entry.isIntersecting;scene.dataset.offscreen=String(!visible);if(visible)update()}).observe(scene);document.addEventListener('visibilitychange',()=>{scene.dataset.offscreen=String(document.hidden||!visible);update()});
 return {update,setStep(value){if(step!==value||!scene.dataset.step){step=value;scene.dataset.step=String(value)}}};
}
