import * as THREE from './vendor/three.module.js';
import {createHandModel} from './hand-landmarks.js';
import {createHRModel} from './hr-workflow.js';
import {createEmployeeModel} from './employee-archive.js';
import {createResumeModel} from './resume-studio.js';

const definitions={
 asl:{title:'THE HAND-LANDMARK PIPELINE',figure:'FIG. 02',color:0x8db2ff,steps:['Landmarks','Features','Classification'],descriptions:['A sculpted hand reveals the 21 spatial landmarks used by the recognition pipeline, from wrist to fingertips.','Selected measurement lines illustrate the 75-feature representation used by Random Forest: coordinates and geometric relationships.','Skeleton images feed MobileNet; engineered features feed Random Forest. Both approaches target 26 alphabet classes. This scene illustrates the pipeline; it does not run inference.']},
 hr:{title:'THE HR DOCUMENT WORKFLOW',figure:'FIG. 03',color:0x8db2ff,steps:['Personnel','Review','Certificate'],descriptions:['An organized personnel register connects each employee profile to the university’s administrative workflows. All records shown are schematic.','Certificate requests pass through an administrative review: employee information, request details, and authorization.','After approval, the application generates a PDF certificate. The raised document and seal illustrate that output.']},
 employee:{title:'THE PERSONNEL ARCHIVE',figure:'FIG. 04',color:0x8db2ff,steps:['Records','Find a profile','Reports'],descriptions:['An indexed archive illustrates how employee profiles, administrative details, and document status stay organized in a structured register.','Search and filters bring a relevant profile out of the register. The moving card illustrates that selection, using schematic information only.','Selected records become a structured export for reporting and administration. The table is illustrative and contains no real employee data.']},
 resume:{title:'A DOCUMENT, BUILT IN LAYERS',figure:'FIG. 05',color:0x8db2ff,steps:['Compose','EN / العربية','PDF'],descriptions:['Experience, education, and skills are editable sections. The separated layers illustrate how those sections come together as a résumé.','Choose English or Arabic above to preview a left-to-right or right-to-left document layout. This is a schematic preview of the builder’s language support.','The assembled résumé becomes a PDF for download. The scene illustrates that output; use the project link to explore the résumé builder.']}
};
let paused=document.body.classList.contains('motion-paused')||matchMedia('(prefers-reduced-motion: reduce)').matches;
const instances=[];
const builders={asl:createHandModel,hr:createHRModel,employee:createEmployeeModel,resume:createResumeModel};

async function mount(host){
 const type=host.dataset.model,def=definitions[type];let renderer;
 try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'low-power'});}catch{return showFallback(host)}
 renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setClearColor(0,0);host.append(renderer.domElement);renderer.domElement.setAttribute('aria-hidden','true');renderer.domElement.setAttribute('tabindex','-1');
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(36,1,.1,50);camera.position.set(0,.65,8.4);camera.lookAt(0,0,0);scene.add(new THREE.HemisphereLight(0xe6f3ff,0x3a4752,2.4));const key=new THREE.DirectionalLight(0xffffff,3.2);key.position.set(-3,5,6);scene.add(key);const fill=new THREE.DirectionalLight(def.color,.8);fill.position.set(4,1,3);scene.add(fill);
 const root=new THREE.Group();scene.add(root);root.rotation.y=-.08;let model;try{model=await builders[type](root,def.color,host);}catch{renderer.domElement.remove();renderer.dispose();return showFallback(host)}model.setStep(0);
 if(type==='asl'||type==='hr'||type==='employee'||type==='resume'){renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;const rim=new THREE.DirectionalLight(0x7daaff,2.3);rim.position.set(1,2,-3);scene.add(rim);}
 host.insertAdjacentHTML('beforeend',`<div class="model-head"><span>${def.title}</span><b>${def.figure} / 3D STUDY</b></div><div class="model-caption"><span>${matchMedia('(pointer: coarse)').matches?'EXPLORE WITH THE CONTROLS BELOW':'DRAG TO ROTATE'}</span><span>CONCEPTUAL MODEL</span></div>`);
 const controls=document.createElement('div');controls.className='model-controls';controls.innerHTML=`<div class="model-step-buttons" role="group" aria-label="Explore ${host.closest('article').querySelector('h3').textContent}">${def.steps.map((label,i)=>`<button type="button" data-model-step="${i}" aria-pressed="${i===0}">${label}</button>`).join('')}</div><p class="model-description" aria-live="polite">${def.descriptions[0]}</p><div class="model-footer"><button type="button" class="model-rotate">Rotate view ↻</button><button type="button" class="model-pause">Pause all motion Ⅱ</button></div>`;host.after(controls);
 const state={host,renderer,scene,camera,root,model,controls,step:0,visible:true,dirty:true,targetX:0,targetY:-.08,dragging:false,dragX:0,dragY:0,autoY:0,time:0};instances.push(state);
 host.addEventListener('model-refresh',()=>{state.dirty=true});
 controls.querySelectorAll('[data-model-step]').forEach(button=>button.addEventListener('click',()=>{state.step=Number(button.dataset.modelStep);host.dataset.step=String(state.step);model.setStep(state.step);controls.querySelectorAll('[data-model-step]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));controls.querySelector('.model-description').textContent=def.descriptions[state.step];state.dirty=true;}));
 controls.querySelector('.model-pause').addEventListener('click',()=>document.dispatchEvent(new CustomEvent('portfolio-toggle-motion')));
 controls.querySelector('.model-rotate').addEventListener('click',()=>{state.targetY+=Math.PI/8;state.dirty=true;});
 const size=()=>{const w=host.clientWidth,h=host.clientHeight-(type==='asl'&&w<=520?(w<=320?165:130):0);renderer.setSize(w,h);model.resize?.(w,h);camera.aspect=w/h;camera.position.z=type==='asl'&&w<=520?10.3:camera.aspect<1?10.5:8.4;camera.updateProjectionMatrix();state.dirty=true};const resizeObserver=new ResizeObserver(size);resizeObserver.observe(host);size();
 renderer.domElement.addEventListener('pointerdown',e=>{if(e.pointerType==='touch')return;state.dragging=true;state.dragX=e.clientX;state.dragY=e.clientY;renderer.domElement.setPointerCapture(e.pointerId)});
 renderer.domElement.addEventListener('pointermove',e=>{if(!state.dragging||paused)return;state.targetY+=Math.max(-.12,Math.min(.12,(e.clientX-state.dragX)*.006));state.targetX=Math.max(-.45,Math.min(.45,state.targetX+(e.clientY-state.dragY)*.004));state.dragX=e.clientX;state.dragY=e.clientY;state.dirty=true});renderer.domElement.addEventListener('pointerup',()=>{state.dragging=false});renderer.domElement.addEventListener('pointercancel',()=>{state.dragging=false});
 const visibilityObserver=new IntersectionObserver(([entry])=>{state.visible=entry.isIntersecting;if(state.visible)state.dirty=true},{rootMargin:'50px'});visibilityObserver.observe(host);
 renderer.domElement.addEventListener('webglcontextlost',event=>{event.preventDefault();state.visible=false;resizeObserver.disconnect();visibilityObserver.disconnect();instances.splice(instances.indexOf(state),1);controls.hidden=true;renderer.domElement.remove();renderer.dispose();showFallback(host)},{once:true});
 host.classList.add('model-ready');host.dataset.modelStatus='ready';host.dataset.step='0';syncButtons();
}
function showFallback(host){if(host.dataset.modelStatus==='fallback')return;host.classList.remove('model-ready');host.dataset.modelStatus='fallback';const p=document.createElement('p');p.className='model-error-note';p.setAttribute('role','status');p.textContent='The interactive model is unavailable in this browser. Project details and links remain available below.';host.after(p)}
function syncButtons(){document.querySelectorAll('.model-pause').forEach(button=>{button.textContent=paused?'Resume all motion ▷':'Pause all motion Ⅱ';button.setAttribute('aria-pressed',String(paused))});instances.forEach(s=>s.dirty=true)}
document.addEventListener('portfolio-motion-change',event=>{paused=event.detail.paused;syncButtons()});
let scrollPending=false;addEventListener('scroll',()=>{if(scrollPending)return;scrollPending=true;requestAnimationFrame(()=>{scrollPending=false;instances.forEach(state=>{if(!state.visible)return;const r=state.host.getBoundingClientRect();state.autoY=Math.max(-.25,Math.min(.25,(r.top+r.height/2-innerHeight/2)/innerHeight*.5));state.dirty=true})})},{passive:true});
let last=performance.now();function render(now){requestAnimationFrame(render);const dt=Math.min((now-last)/1000,.04);last=now;if(document.hidden)return;for(const s of instances){if(!s.visible)continue;if(paused&&!s.dirty)continue;if(!paused)s.time+=dt;const amount=paused?1:.07;s.root.rotation.y=THREE.MathUtils.lerp(s.root.rotation.y,s.targetY+(paused?0:s.autoY),amount);s.root.rotation.x=THREE.MathUtils.lerp(s.root.rotation.x,s.targetX,amount);s.model.update(s.time,s.step,paused);s.renderer.render(s.scene,s.camera);s.dirty=false;}}requestAnimationFrame(render);
const lazy=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting){lazy.unobserve(entry.target);mount(entry.target)}},{rootMargin:'250px'});document.querySelectorAll('[data-model]').forEach(host=>lazy.observe(host));
